title: <p align="center"> Victoria Ghielmetti </p>

logo: "/images/github picture 1.4.24 v4.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Victoria Ghielmetti Resume 12.22.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vghielmetti/">LinkedIn</a> |
  <a href="https://github.com/vghielme">GitHub</a>
  </p>
  
  <p align="justify">
  Strategic and proactive Data Analyst with 5+ years of experience in data analytics, technical project management, operations streamlining, and risk mitigation for executive leadership teams and 10 years of experience in customer service. Adept at using Python, SQL, Power BI, and advanced Excel to enhance product efficiencies. 
  <br><br>
  Risk Mitigation, Complex Problem Solving, Technical Project Management, Data Analytics, Data Extraction, Data Cleaning, Stakeholder Collaboration, Dashboard and eporting Design
  <br><br>
  </p>

theme: jekyll-theme-minimal
  
