title: <p align="center"> Victoria Ghielmetti </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Victoria Ghielmetti Resume 12.22.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vghielmetti/">LinkedIn</a> |
  <a href="https://github.com/vghielme">GitHub</a>
  </p>
  
  <p align="justify">
  Professional Profile: Strategic and proactive Data Analyst with 5+ years of experience in data analytics, technical project management, operations streamlining, and risk mitigation for executive leadership teams and 10 years of experience in customer service. Adept at using Python, SQL, Power BI, and advanced Excel to enhance product efficiencies. Quick study who loves data and is always eager to learn more.
  <br><br>
  Professional Profile: Strategic and proactive Data Analyst with 5+ years of experience in data analytics, technical project management, operations streamlining, and risk mitigation for executive leadership teams and 10 years of experience in customer service. Adept at using Python, SQL, Power BI, and advanced Excel to enhance product efficiencies. Quick study who loves data and is always eager to learn more.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
